# Generated by Django 4.1.3 on 2022-12-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-12-23'),
            preserve_default=False,
        ),
    ]
